title: Movie saga
description: >-
  The best place to find in which order you can or should watch your favorite movie sagas !
baseurl: "/"
url: "https://movie-saga.com/"

collections_dir: database
collections:
  sagas:
    output: true
  orders:
    output: true
